# BookExport configuration

# Where to store the exported books .txt files?
# Default is plugins/BookExport/books/
#
# Types supported:
# - Relative folder name (recommended):
#     "books"
#     -> plugins/BookExport/books/
#
# - Another relative name:
#     "some-books"
#     -> plugins/BookExport/some-books/
#
# - Full absolute path:
#     "/path/to/some/folder/exported_books/"
#
# - From the server root using "~/":
#     "~/plugins/CMI/CustomText/"
#     -> <server root>/plugins/CMI/CustomText/
#
# If empty, BookExport will use the plugin data folder: plugins/BookExport/
exported-books-directory: "books"

# Include pagination at all?
# true  - include a pagination marker before each page
# false - no pagination marker, just plain text pages separated by blank lines
pagination: true

# In the .txt file, how should pagination show when enabled?
# Default is: === Page 1 ===
# For CMI ctext compatibility you might want: "<NextPage>"
#
# Use %pageNumber% as an internal placeholder to show the correct page number in that location.
# Examples:
#   "=== Page %pageNumber% ==="
#   "<NextPage>"
pagination-markup: "=== Page %pageNumber% ==="

# Include book meta data such as author, date, etc?
# Example:
# Title: ยง71MBNews-April
# Author: Server
# Exported by: mrfloris
# Exported at: 2025-11-22T08:46:20.028303
#
# true  - include this metadata header at the top of the file
# false - skip it, only export the raw text
book-meta: true
